-- zht_study / studyplatform database initialization
-- Target: MySQL 5.7+
--
-- This script is reconstructed from the entity classes and MyBatis mapper XML
-- files in this project. It is safe to run repeatedly: existing tables and
-- rows are retained.
--
-- Demo accounts (the current application compares plain-text passwords):
--   administrator: phone 13800000000 / password admin123
--   normal user:   phone 13900000000 / password user123

CREATE DATABASE IF NOT EXISTS `studyplatform`
    DEFAULT CHARACTER SET utf8mb4
    DEFAULT COLLATE utf8mb4_unicode_ci;

USE `studyplatform`;

SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS `user` (
    `userID` INT NOT NULL COMMENT 'User ID generated by the application',
    `userName` VARCHAR(50) NOT NULL COMMENT 'Display name',
    `password` VARCHAR(100) NOT NULL COMMENT 'Login password',
    `gender` CHAR(1) DEFAULT NULL COMMENT 'Gender',
    `birth` VARCHAR(20) DEFAULT NULL COMMENT 'Birth date stored by the legacy application',
    `phone` VARCHAR(20) NOT NULL COMMENT 'Login phone number',
    `role` INT NOT NULL DEFAULT 0 COMMENT '0: normal user, 1: administrator',
    `head` VARCHAR(255) DEFAULT NULL COMMENT 'Avatar path',
    PRIMARY KEY (`userID`),
    UNIQUE KEY `uk_user_phone` (`phone`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Users';

CREATE TABLE IF NOT EXISTS `category` (
    `categoryid` INT NOT NULL,
    `categoryName` VARCHAR(100) NOT NULL,
    PRIMARY KEY (`categoryid`),
    UNIQUE KEY `uk_category_name` (`categoryName`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Course categories';

CREATE TABLE IF NOT EXISTS `course` (
    `courseID` INT NOT NULL,
    `courseName` VARCHAR(100) NOT NULL,
    `categoryid` INT NOT NULL,
    `content` VARCHAR(1000) DEFAULT NULL COMMENT 'Course introduction',
    `teacherName` VARCHAR(50) DEFAULT NULL,
    `selectNum` INT NOT NULL DEFAULT 0 COMMENT 'Number of selections',
    `uploadtime` VARCHAR(30) DEFAULT NULL COMMENT 'Legacy string-formatted publish time',
    PRIMARY KEY (`courseID`),
    KEY `idx_course_category` (`categoryid`),
    KEY `idx_course_name` (`courseName`),
    CONSTRAINT `fk_course_category`
        FOREIGN KEY (`categoryid`) REFERENCES `category` (`categoryid`)
        ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Courses';

CREATE TABLE IF NOT EXISTS `selectcourses` (
    `userID` INT NOT NULL,
    `courseID` INT NOT NULL,
    `select` INT NOT NULL DEFAULT 1 COMMENT '0: withdrawn, 1: selected',
    `downpath` VARCHAR(255) DEFAULT NULL COMMENT 'Download path',
    `downtime` VARCHAR(30) DEFAULT NULL COMMENT 'Legacy string-formatted download time',
    `note` VARCHAR(1000) DEFAULT NULL COMMENT 'Course note',
    `notetime` VARCHAR(30) DEFAULT NULL COMMENT 'Legacy string-formatted note time',
    PRIMARY KEY (`userID`, `courseID`),
    KEY `idx_selectcourses_course` (`courseID`),
    CONSTRAINT `fk_selectcourses_user`
        FOREIGN KEY (`userID`) REFERENCES `user` (`userID`)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT `fk_selectcourses_course`
        FOREIGN KEY (`courseID`) REFERENCES `course` (`courseID`)
        ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Course selections and notes';

CREATE TABLE IF NOT EXISTS `review` (
    `courseid` INT NOT NULL,
    `userid` INT NOT NULL,
    `review` VARCHAR(1000) DEFAULT NULL,
    `reviewtime` VARCHAR(30) DEFAULT NULL COMMENT 'Legacy string-formatted review time',
    PRIMARY KEY (`courseid`, `userid`),
    KEY `idx_review_user` (`userid`),
    CONSTRAINT `fk_review_course`
        FOREIGN KEY (`courseid`) REFERENCES `course` (`courseID`)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT `fk_review_user`
        FOREIGN KEY (`userid`) REFERENCES `user` (`userID`)
        ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Course reviews';

CREATE TABLE IF NOT EXISTS `log` (
    `courseID` INT NOT NULL,
    `userID` INT NOT NULL,
    PRIMARY KEY (`courseID`, `userID`),
    KEY `idx_log_user` (`userID`),
    CONSTRAINT `fk_log_course`
        FOREIGN KEY (`courseID`) REFERENCES `course` (`courseID`)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT `fk_log_user`
        FOREIGN KEY (`userID`) REFERENCES `user` (`userID`)
        ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='User-course access log';

-- The next two tables are queried by PersonalCenterMapper and mapped directly
-- to the History and Learning entity classes.
CREATE TABLE IF NOT EXISTS `history` (
    `courseId` INT NOT NULL,
    `userId` INT NOT NULL,
    `courseName` VARCHAR(100) NOT NULL,
    `learnDate` VARCHAR(30) DEFAULT NULL,
    `url` VARCHAR(255) DEFAULT NULL,
    `progress` INT NOT NULL DEFAULT 0 COMMENT 'Percentage from 0 to 100',
    PRIMARY KEY (`courseId`, `userId`),
    KEY `idx_history_user` (`userId`),
    CONSTRAINT `fk_history_course`
        FOREIGN KEY (`courseId`) REFERENCES `course` (`courseID`)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT `fk_history_user`
        FOREIGN KEY (`userId`) REFERENCES `user` (`userID`)
        ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Learning history';

CREATE TABLE IF NOT EXISTS `learning` (
    `courseId` INT NOT NULL,
    `userId` INT NOT NULL,
    `courseName` VARCHAR(100) NOT NULL,
    `selectNumber` INT NOT NULL DEFAULT 0,
    `teacher` VARCHAR(50) DEFAULT NULL,
    `content` VARCHAR(1000) DEFAULT NULL,
    `url` VARCHAR(255) DEFAULT NULL,
    `link` VARCHAR(255) DEFAULT NULL,
    `progress` VARCHAR(50) DEFAULT NULL COMMENT 'Chapter/progress label',
    PRIMARY KEY (`courseId`, `userId`),
    KEY `idx_learning_user` (`userId`),
    CONSTRAINT `fk_learning_course`
        FOREIGN KEY (`courseId`) REFERENCES `course` (`courseID`)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT `fk_learning_user`
        FOREIGN KEY (`userId`) REFERENCES `user` (`userID`)
        ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Current learning courses';

INSERT IGNORE INTO `user`
    (`userID`, `userName`, `password`, `gender`, `birth`, `phone`, `role`, `head`)
VALUES
    (20001, '系统管理员', 'admin123', '男', '1990-01-01', '13800000000', 1, '/static/userinfo/img/avatar-0.jpg'),
    (10001, '演示用户',   'user123',  '女', '1998-06-15', '13900000000', 0, '/static/userinfo/img/avatar-1.jpg');

INSERT IGNORE INTO `category` (`categoryid`, `categoryName`)
VALUES
    (1, 'Java'),
    (2, 'C/C++'),
    (3, '数据库'),
    (4, 'Web前端');

INSERT IGNORE INTO `course`
    (`courseID`, `courseName`, `categoryid`, `content`, `teacherName`, `selectNum`, `uploadtime`)
VALUES
    (1001, 'Java实现权限管理（下）', 1, '通过一个完整案例学习 Java Web 权限管理的设计与实现。', '张老师', 54, '2019-05-20'),
    (1002, 'C++远征之模板篇',       2, '介绍函数模板、类模板以及模板在工程实践中的常见用法。',   '李老师', 32, '2019-05-21'),
    (1003, 'Java实现权限管理（上）', 1, '从用户、角色和权限模型开始搭建 Java Web 权限管理基础。',   '张老师', 54, '2019-05-18'),
    (1004, 'C++远征之多态篇',       2, '学习虚函数、抽象类和运行时多态。',                         '李老师', 32, '2019-05-17'),
    (1005, 'C++远征之继承篇',       2, '学习继承关系、访问控制与对象构造顺序。',                   '李老师', 54, '2019-05-16'),
    (1006, 'C++远征之起航篇',       2, '面向初学者的 C++ 基础语法与开发环境入门。',                '李老师', 32, '2019-05-15');

INSERT IGNORE INTO `selectcourses`
    (`userID`, `courseID`, `select`, `downpath`, `downtime`, `note`, `notetime`)
VALUES
    (10001, 1001, 1, '/static/zui/video/10001.mp4', NULL, '复习角色与权限之间的关系。', '2019-06-05 10:30:00'),
    (10001, 1002, 1, '/static/zui/video/10001.mp4', NULL, '整理模板参数的常见写法。',     '2019-06-05 11:00:00'),
    (10001, 1004, 0, '/static/zui/video/10001.mp4', NULL, NULL,                         NULL);

INSERT IGNORE INTO `review` (`courseid`, `userid`, `review`, `reviewtime`)
VALUES
    (1001, 10001, '课程讲解清晰，案例很实用。', '2019-06-05 12:00:00'),
    (1002, 10001, '模板部分的例子容易理解。',   '2019-06-05 12:10:00');

INSERT IGNORE INTO `log` (`courseID`, `userID`)
VALUES
    (1001, 10001),
    (1002, 10001);

INSERT IGNORE INTO `history`
    (`courseId`, `userId`, `courseName`, `learnDate`, `url`, `progress`)
VALUES
    (1001, 10001, 'Java实现权限管理（下）', '2019-06-05 10:30:00', '/static/image/java_1_2.jpg', 50),
    (1002, 10001, 'C++远征之模板篇',       '2019-06-05 11:00:00', '/static/image/course_c++_4.jpg', 30),
    (1003, 10001, 'Java实现权限管理（上）', '2019-06-04 16:20:00', '/static/image/java_1_1.jpg', 70);

INSERT IGNORE INTO `learning`
    (`courseId`, `userId`, `courseName`, `selectNumber`, `teacher`, `content`, `url`, `link`, `progress`)
VALUES
    (1001, 10001, 'Java实现权限管理（下）', 54, '张老师', '通过一个完整案例学习 Java Web 权限管理的设计与实现。', '/static/image/java_1_2.jpg', '/studycenter/index?courseId=1001', '第一章'),
    (1002, 10001, 'C++远征之模板篇',       32, '李老师', '介绍函数模板、类模板以及模板在工程实践中的常见用法。',   '/static/image/course_c++_4.jpg', '/studycenter/index?courseId=1002', '第二章');
